# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvvI4MEIg3d7WpFDcVhgCScfP4ztwJ76

### **Streamlit Application Code**

I'll organize the code into functions and use `st.cache_resource` to avoid re-running expensive computations every time the app reloads. This will make your Streamlit app much more efficient.
"""

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel
import numpy as np

@st.cache_resource
def load_and_preprocess_data():
    credits = pd.read_csv("https://raw.githubusercontent.com/ashishpatel26/Content-Based-Recommender-System/main/tmdb_5000_credits.csv")
    movies_df = pd.read_csv("https://raw.githubusercontent.com/ashishpatel26/Content-Based-Recommender-System/main/tmdb_5000_movies.csv")

    credits_column_renamed = credits.rename(index=str, columns={"movie_id": "id"})
    movies_df_merge = movies_df.merge(credits_column_renamed, on='id')

    movies_cleaned_df = movies_df_merge.drop(columns=['homepage', 'title_x', 'title_y', 'status','production_countries'])

    # Filling NaNs with empty string for 'overview'
    movies_cleaned_df['overview'] = movies_cleaned_df['overview'].fillna('')

    return movies_cleaned_df


def compute_similarity_matrix(movies_cleaned_df):
    tfv = TfidfVectorizer(min_df=3, max_features=None,
                          strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
                          ngram_range=(1, 3),
                          stop_words = 'english')

    tfv_matrix = tfv.fit_transform(movies_cleaned_df['overview'])
    sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

    # Reverse mapping of indices and movie titles
    indices = pd.Series(movies_cleaned_df.index, index=movies_cleaned_df['original_title']).drop_duplicates()

    return sig, indices

def give_rec(title, sig, movies_cleaned_df, indices):
    # Get the index corresponding to original_title
    if title not in indices:
        return [] # Return empty list if movie not found
    idx = indices[title]

    # Get the pairwise similarity scores
    sig_scores = list(enumerate(sig[idx]))

    # Sort the movies
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)

    # Scores of the 10 most similar movies
    sig_scores = sig_scores[1:11]

    # Movie indices
    movie_indices = [i[0] for i in sig_scores]

    # Top 10 most similar movies
    return movies_cleaned_df['original_title'].iloc[movie_indices]

"""### **Run the Streamlit App**

To run this Streamlit app, save your notebook (File -> Save) and then execute the following command in your Colab terminal (accessible from the bottom left panel):

```bash
streamlit run /content/<your_notebook_name>.ipynb
```

Replace `<your_notebook_name>.ipynb` with the actual name of your notebook file. A public URL will be provided in the output, which you can click to view your app.
"""

# Main Streamlit app logic

st.title("Movie Recommender System")

movies_cleaned_df = load_and_preprocess_data()
sig, indices = compute_similarity_matrix(movies_cleaned_df)

movie_list = movies_cleaned_df['original_title'].values

selected_movie = st.selectbox("Select a movie", movie_list)

if st.button("Recommend"):
    if selected_movie:
        recommended_movie_names = give_rec(selected_movie, sig, movies_cleaned_df, indices)
        st.subheader(f"Recommendations for '{selected_movie}':")
        if recommended_movie_names.empty:
            st.write("No recommendations found.")
        else:
            for i, movie_name in enumerate(recommended_movie_names):
                st.write(f"{i+1}. {movie_name}")
    else:
        st.write("Please select a movie to get recommendations.")
